spring:
  application:
    name: msvc-subject
  datasource:
    url: jdbc:postgresql://localhost:5432/school_system
    username: postgres
    password: root
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show:
      sql: true
    properties:
      hibernate:
        format_sql: true
        properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE