server:
  port: 8082
spring:
  application:
    name: msvc-subject
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop