spring:
  application:
    name: msvc-students
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/SchoolSystem
    username: postgres
    password: postgres

server:
  port: 8081

springdoc:
  swagger-ui.path: /swagger-ui.html