server:
  port: 8083
spring:
  application:
    name: msvc-teacher
  datasource:
    url: jdbc:postgresql://localhost:5432/school_system
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
